language: node_js
jobs:
  include:
    - stage: build
      script: "npm install"
    - stage: test
      script: "npm run test"
    - stage: lint
      script:
        - "npm run eslint"
        - "npm run jscpd"